### ISSUE TITLE
[Chore] 예약 조회/ 프로필 조회 기능 수정

### ISSUE THREAD

**Issue by daeun084** [MEME-UMC/MEME_SERVICE#59]
## 💡 Description

- Artist, Model이 User Entity를 상속받도록 코드를 수정합니다
- artist/model의 예약 조회/프로필 조회 기능을 하나로 합칩니다

## 📝  Progress

- [x] user entity 상속
- [x] 예약 조회 합치기
- [x] 프로필 조회 합치기

**Comment by woongaaaa** [comment]
_**메메 화이팅**_
